name: pagination_plus
description: >
  A lightweight, responsive Flutter pagination widget with customizable rows, page controls, and support for desktop, tablet, and mobile.

version: 1.0.7

# Links
homepage: https://github.com/romil-narola/flutter_pagination
repository: https://github.com/romil-narola/flutter_pagination

# SDK version
environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.10.0"

# Package dependencies
dependencies:
  flutter:
    sdk: flutter

# Development & testing dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0
  lints: ^3.0.0

# Optional: Tag categories to help pub.dev categorize the package
topics:
  - pagination
  - widgets
  - flutter
  - responsive

# Optional: Pub score suggestions
flutter:
  uses-material-design: true
